<?php
    require_once '../classes/artworks.php';
	include_once '../scripts/in_memory_functions.php';
	session_start();	
	include_once "../classes/images.php";
	include_once "../classes/shows.php";
	include_once "../constants.php";
	include_once 'scripts/save.php';
    include_once "../scripts/load.php"; 

$works = load_art($db, 'all', true); // include the archived images

$cats = ['social','abstract','figurative','landscape'];

$social = [
    "apartheidwall",    "Apartheid Wall",       "2016",     "oil on canvas",        "48 x 52",     "available",
    "myfish",           "My Fish",             "2018",     "oil on canvas",      "48 x 52",    "available",
    "mylife",           "MY Life",             "2018",     "oil on canvas",      "40 x 50",    "available",
    "pondbank",         "Pond Bank",           "2018",     "oil on canvas",      "48 x 52",   "available",
    "darwin",           "Darwin",              "2018",     "oil on canvas",      "48 x 36",   "available",
    "transitioning",    "Transitioning",       "2018",     "oil on canvas",      "48 x 48",   "available",
    "metoo",             "Me Too",             "2018",     "oil on canvas",       "40 x 50",   "available",
    "rehistory",        "Rehistory",           "2018",     "oil on canvas",       "38 x 54",   "available", 
    "potatoman",        "Potato Man",          "2017",     "oil on canvas",       "36 x 54",   "available",
    "lampshade",        "Lamp Shade",          "2017",     "oil on canvas",       "36 x 48",    "available",
    "thinker",          "Thinker",             "2017",     "oil on canvas",        "36 x 54",   "availabe",
    "dreamerbeing",     "Dreamer Being",        "2017",     "oil on canvas",        "36 x 54",  "available",
    "timetoask",        "Time To Ask",         "2017",     "oil on canvas",        "48 x 58",  "available", 
    "treeoflife",      "Tree Of Life",         "2017",     "oil on canvas",        "48 x 52",    "available",  
    "breakingfree",    "Breaking Free",        "2017",     "oil on canvas",        "48 x 52",   "available",
    "xcolumbus",        "X Columbus",          "2017",      "oil on canvas",       "48 x 58",  "available",
    "moms",              "Moms",               "2017",     "oil on canvas",       "42 x 50",    "available",
    "dreamers",         "Dreamers",            "2017",     "oil on canvas",       "44 x 52",    "available",
    "myteddie",         "My Teddie",           "2017",     "oil on canvas",        "44 X 50",    "available",
    "twospirit",        "Two Spirit",          "2017",     "oil on canvas",       "48 x 52",    "available",
    "homeless",         "Homeless",            "2017",     "oil on canvas",       "48 x 60",    "available",
    "shawneeme",        "Shawnee Me",          "2017",     "oil on canvas",        "36 x 72",   "sold",
    "meetmikex",        "Meet Mike X",         "2017",     "oil on canvas",        "48 x 52",   "available",
    "variations",       "Variations",          "2017",     "oil on canvas",        "48 x 52",   "available",
    "closetexit",       "Closet Exit",          "2017",     "oil on canvas",        "44 x 50",    "available",
    "testify",          "Testify",             "2017",     "oil on canvas",        "47 x 56",   "available",
    "oldwest",          "Old West",            "2017",     "oil on canvas",        "56 x 48",   "available",
    "longterm",         "Long Term",           "2017",     "oil on canvas",        "36 x 48",   "available",   
    "whatsin",          "What Sin",            "2017",     "oil on canvas",        "36 x 48",    "sold",   
    "ghostdance",       "Ghost Dance",          "2017",    "oil on canvas",        "50 x 56",    "available",
    "corporatekillers",  "Corporate Killers",   "2017",    "oil on canvas",        "48 x 50",   "available",
    "higherpower",       "Higher Power",         "2017",     "oil on canvas",        "36 x 54",   "available",
    "loveworks",        "Love Works",          "2017",     "oil on canvas",        "36 x 48",    "available",
    "gayarrow",         "Gay Arrow",           "2017",     "oil on canvas",        "36 x 24",   "available",  
    "whitegloves",      "White Gloves",        "2017",     "oil on canvas",        "30 x 48",   "available",
    "freeingeve",       "Freeing Eve",         "2017",     "oil on canvas",        "30 x 48",    "available",
    "missbingo",        "Miss Bingo",          "2017",     "oil on canvas",        "30 x 48",   "available",
    "poisonwater",      "Poison Water",        "2017",     "oil on canvas",        "42 x 36",   "available",
    "norefuge",         "No Refuge",           "2017",     "oil on canvas",        "40 x 48",  "available",
    "mothersunite",     "Mothers Unite",       "2017",     "oil on canvas",        "54 x 70",  "available",
    "angelup",          "Angel Up",            "2017",     "oil on canvas",        "46 x 54",  "sold",
    "earthishome",      "Earth Is Home",       "2017",     "oil on canvas",        "36 x 48",   "available",
    "dreamer1",         "Dreamer 1",           "2017",     "oil on canvas",        "36 x 48",   "available",
    "dreamer2",         "Dreamer 2",           "2017",     "oil on canvas",        "36 x 48",   "sold",
    "candy",            "Candy",               "2017",      "oil on canvas",       "36 x 48",   "available",
    "crossingover",     "Crossing Over",       "2017",      "oil on canvas",       "36 x 48",   "available",  
    "heroincrisis",     "Heroin Crisis",      "2017",      "oil on canvas",       "44 x 52",   "sold",
    "loveislove",       "Love is Love",        "2016",      "oil on canvas",       "44 x 56",   "available",
    "corporatewars",    "Corporate Wars",      "2016",      "oil on canvas",       "36 x 48",   "available",
    "ksspots",          "K S Spots",           "2016",      "oil on canvas",       "48 x 48",    "sold",
    "openprison",      "Open Prison",          "2016",      "oil on canvas",        "48 x 50",   "available",
    "cosmicdance",     "Cosmic Dance",         "2016",      "oil on canvas",        "46 x 56",   "sold",
    "hellopeeps",       "Hello Peeps",          "2016",     "oil on canvas",       "48 x 54",    "available",
    "gendervariable",  "Gender Variable",      "2016",      "oil on canvas",        "48 x 48",   "sold",
    "momstribe",        "Moms Tribe",           "2016",     "oil on canvas",        "48 x 54",    "sold",
    "kidsinwar",        "Kids In War",          "2016",     "oil on canvas",        "42 x 48",   "available",
    "collateraldamage", "Collateral Damage",    "2016",     "oil on canvas",        "48 x 56",    "available",
    "lostpapoose",      "Lost Papoose",         "2016",     "oil on canvas",        "46 x 58",    "available",
    "nammyoho",         "Nam Myo Ho",           "2016",     "oil on canvas",        "43 x 62",    "available",
    "teapots",          "Tea Pots",             "2016",     "oil on canvas",        "48 x 58",    "sold",
    "safepassage",      "Safe Passage",         "2016",     "oil on canvas",        "48 x 30",    "available",
    "refugeesprayers",  "Refugees Prayers",     "2016",     "oil on canvas",        "42 x 46",    "available",
    "myride",           "My Ride",              "2016",     "oil on canvas",        "56 x 70",    "available",
    "shamanbird",       "Shaman Bird",          "2016",     "oil on canvas",        "44x54",      "available",
    "childofwar",       "Child Of War",         "2016",     "oil on canvas",        "54 x 64",     "available",
    "freeflotilla",     "Free Flotilla",        "2016",     "oil on canvas",        "48.5 x 53",   "available",
    "peacedance",       "Peace Dance",          "2016",     "oil on canvas",        "46 x 52",     "available",
    "secretisland",     "Secret Island",        "2016",     "oil on canvas",        "48 x 58",     "available",
    "shastaboat",       "Shasta Boat",          "2016",     "oil on canvas",        "30 x 24",     "sold",  
    "warzone",           "War Zone",            "2016",     "oil on canvas",        "48 x 52",     "available",
    "warschild",       "War's Child",           "2015",     "oil on canvas",        "48 x 60",     "sold",
    "refugees",         "Refugees",             "2015",     "oil on canvas",        "48 x 54",     "sold",
    "totem",            "Totem",                "2015",     "oil on canvas",        "44 x 50",     "available",
    "narrative",        "Narrative",            "2015",     "oil on canvas",        "62 x 54",     "available",
    "focus",            "Focus",                "2015",     "oil on canvas",        "48 x 54",     "sold",
    "indigenous",       "Indigenous",           "2015",     "oil on canvas",        "48 x 54",     "sold",
    "exhibitionist",    "Exhibitionist",        "2015",     "oil on canvas",        "46 x 58",     "sold",
    "headsup",          "Heads Up",             "2015",     "oil on canvas",        "54 x 64",     "available",
    "hetwirls",         "He Twirls",            "2015",     "oil on canvas",        "48 x 54",     "sold",
    "wonderland",       "Wonderland",           "2015",     "oil on canvas",        "49 x 72",     "available",
    "myshaman",         "My Shaman",            "2015",     "oil on canvas",        "48 x 56",     "sold",
    "mywarrior",        "My Warrior",           "2015",     "oil on canvas",        "48 x 60",     "available",
    "myoffering",       "My Offering",          "2015",     "oil on canvas",        "48 x 54",     "sold",
    "uplayground",      "U Playground",         "2015",     "oil on canvas",        "48 x 56",     "sold",
    "holycow",          "Holy Cow",             "2015",     "oil on canvas",        "48 x 58",     "sold",
    "kachinaman",       "Kachina Man",          "2015",     "oil on canvas",        "48 x 52",     "available",
    "observationroom",  "Observation Room",     "2015",     "oil on canvas",        "60 x 57.5",   "available",
    "lady",             "Lady",                 "2015",     "oil on canvas",        "54 x 64",     "sold",
    "inplay",           "In Play",              "2015",     "oil on canvas",        "34 x 42",     "sold",
    "fruitloops",       "Fruit Loops",          "2015",     "oil on canvas",        "43 x 62",     "sold",
    "freemove",         "Free Move",            "2015",     "oil on canvas",        "56 x 70",     "sold",
    "placement",        "Placement",            "2015",     "oil on canvas",        "48 x 58",     "sold",
    "allsides",         "All Sides",            "2015",     "oil on canvas",        "48 x 60",     "sold",
    "indiomex",         "Indio Mex",            "2014",     "oil on canvas",        "60 x 60",      "available",
    "mycocoon",          "My Cocoon",           "2014",     "oil on canvas",        "48 x 54",      "sold",
    "hostage",          "Hostage",              "2014",     "oil on canvas",        "48 x 58",      "sold",
    "flotilla",         "Flotilla",             "2014",     "oil on canvas",        "48 x 30",      "sold",
    "myperception",     "My Perception",        "2014",     "oil on canvas",        "54 x 65",      "available",
    "reborn",           "Reborn",               "2014",     "oil on canvas",        "48 x 54",      "available",
    "metro",            "Metro",                "2014",     "oil on canvas",        "48 x 72",      "available",
    "shatteredman",     "Shattered Man",        "2014",     "oil on canvas",        "48 x 52",      "sold",
    "loversboat",       "loversboat",           "2014",     "oil on canvas",        "48 x 48",      "sold",
    "mytransport",      "My Transport",         "2014",     "oil on canvas",        "48 x 54",      "sold",
    "lifeboat",         "Life Boat",            "2014",     "oil on canvas",        "48 x 54",      "available",
    "tribaldeath",      "Tribal Death",         "2014",     "oil on canvas",        "36 x 48",      "sold",
    "doerayme",         "Doe Ray Me",           "2014",     "oil on canvas",        "58 x 46",      "sold",
    "basic",            "Basic",                "2014",     "oil on canvas",        "24 x 30.5",    "sold",
    "overrainbow",      "Over The Rainbow",     "2014",     "oil on canvas",        "44 x 54",      "sold",
    "journeyhome",      "Journey Home",         "2014",     "oil on canvas",        "84 x 52",      "sold",
    "glasshouses",      "Glass Houses",         "2013",     "oil on canvas",        "56 x 48",      "sold",
    "manashore",        "Man Ashore",           "2013",     "oil on cansas",        "54 x 48",      "sold",
    "yippiekayay",      "Yippie Ka Yay",        "2014",     "oil on canvas",        "60 x 54",      "available",
    "sfcity",           "SF City",              "2013",     "oil on canvas",        "64 x 52",      "sold",
    "goldengate",       "Golden Gate",          "2013",     "oil on canvas",        "52 x 59",      "sold",
    "construction",     "Construction",         "2013",     "oil on canvas",        "48 x 60",      "sold",
    "smooth",           "Smooth",               "2013",     "oil on canvas",        "24 x 30",      "sold",
    "inspired",         "Inspired",             "2013",     "oil on canvas",        "36 x 48",      "sold",
    "freechelsea",      "Free Chelsea",         "2013",     "oil on canvas",        "58 x 48",      "sold",
    "brokencommandments","Broken Commandments", "2013",     "oil on canvas",        "58 x 48",      "sold",
    "fracking",         "Fracking",             "2013",     "oil on canvas",        "44 x 54",      "available",
    "facility",         "Facility",             "2013",     "oil on canvas",        "42 x 48",      "sold",
    "tension",          "Tension",              "2013",     "oil on canvas",        "48 x 84",      "available",
    "shastafind",       "Shasta Find",          "2013",     "oil on canvas",        "36 x 48",      "sold",
    "frostco",          "Frostco",              "2013",     "oil on canvas",        "24 x 36",      "sold",  
    "pushingatmosphere", "Pushing Atmosphere",  "2013",     "oil on canvas",        "24 x 36",      "sold",
    "arrived",          "Arrived",              "2013",     "oil on canvas",        "36 x 48",      "sold",
    "glasshouse",       "Glass House",          "2013",     "oil on canvas",        "60 x 70",      "available", 
    "jumpout",          "Jump out",             "2013",     "oil on canvas",        "36 x 48",      "available",
    "fireglass",        "Fire Glass",           "2013",     "oil on canvas",        "48 x 60",      "sold",
    "spotlight",        "Spot Light",           "2013",     "oil on canvas",        "84 x 52",      "sold",  
    "crossandarrow",    "Cross and Arrow",      "2013",     "oil on canvas",        "60 x 44",      "available",
    "birdisland",       "Bird Island",          "2013",     "oil on canvas",        "30 x 40",      "available",   
    "angeldance",       "Angel Dance",          "2013",     "oil on canvas",        "48 x 48",      "sold",
    "nocolumbus",       "No Columbus",          "2013",     "oil on canvas",        "46 x 56",      "sold",   
    "structure",        "Structure",            "2013",     "oil on canvas",        "60 x 66",      "available",
    "lookingwindow",    "Looking Window",       "2013",     "oil on canvas",        "44 x 52",      "sold",
    "profile",          "Profile",              "2013",     "oil on canvas",        "52 x 54",      "available",
    "fixed",            "Fixed",                "2013",     "oil on canvas",        "48 x 84",      "sold",
    "elchair",          "El Chair",             "2013",     "oil on canvas",        "54 x 70",      "sold",
    "stopwar",          "Stop War",             "2013",     "oil on canvas",        "46 x 58",      "available",
    "whalecity",        "Whale City",           "2012",     "oil on canvas",        "48 x 58",      "available",
    "collapse2",        "Collapse 2",           "2012",     "oil on canvas",        "36 x 48",      "sold",
    "inbox",            "In Box",               "2012",     "oil on canvas",        "36 x 48",      "available",
    "heisthere",        "He is There",          "2012",     "oil on canvas",        "54 x 65",      "sold",
    "horsecity",        "Horse City",           "2012",     "oil on canvas",        "46 x 50",      "sold",
    "whalecity",        "Whale City",           "2012",     "oil on canvas",        "48 x 58",      "sold",
    "pulloff",          "Pull Off",             "2012",     "oil on canvas",        "48 x 80",      "available",
    "la boot",          "La Boot",              "2012",     "oil on canvas",        "48 x 56",      "sold",
    "perception",       "Perception",           "2012",     "oil on canvas",        "48 x 56",      "available",
    "complexity",       "Complexity",           "2012",     "oil on canvas",        "48 x 56",      "available",
    "sf101",            "S.F.101",              "2012",     "oil on canvas",        "48 x 56",      "available",
    "patching",         "Patching",             "2012",     "oil on canvas",        "48 x 56",      "sold",
    "shattered",        "Shattered",            "2012",     "oil on canvas",        "62 x 62",      "available",
    "staircase",        "Staircase",            "2012",     "oil on canvas",        "56 x 60",      "sold",
    "myquilt",          "My Quilt",             "2012",     "oil on canvas",        "48 x 58",      "sold",
    "canoe&teepee",     "Canoe & Tee Pees",     "2012",     "oil on canvas",        "60 x 48",      "sold",
    "splash",           "Splash",               "2012",     "oil on canvas",        "36 x 48",      "sold",
    "popnscratch",      "Pop n Scratch",        "2012",     "oil on canvas",        "48 x 58",      "available",
    "brokenboat",       "Broken Boat",          "2012",     "oil on canvas",        "80 x 44",      "available",
    "tugboat",           "Tug Boat",            "2012",     "oil on canvas",        "56 x 48",      "sold",
    "twincity",         "Twin City",            "2012",     "oil on canvas",        "44 x 80",      "sold",
    "frontier",         "Frontier",             "2012",     "oil on canvas",        "44 x 52",      "sold",
    "shiplegs",         "Ship Legs",            "2012",     "oil on canvas",        "56 x 44",      "sold",  
    "overthehill",      "Over The Hill",        "2012",     "oil on canvas",        "52 x 44",      "sold",
    "houseboat",        "House Boat",           "2012",     "oil on canvas",        "60 x 72",      "sold",
    "downlow",          "Down Low",             "2012",     "oil on canvas",        "60 x 65",      "sold",
    "softmist",         "Soft Mist",            "2012",     "oil on canvas",        "36 x 48",      "sold",
    "urbanself",        "Urban Self",           "2012",     "oil on canvas",        "52 x 59",      "sold",
    "overcast",         "Over Cast",            "2012",     "oil on canvas",        "60 x 57.5",    "sold", 
    "thedig",           "The Dig",              "2012",     "oil on cnvas",         "44 x 50",      "sold",
    "shipwrecked",      "Ship Wrecked",         "2012",     "Oil on Canvas",        "44 x 50",      "sold",
    "mypatches",        "My Patches",           "2012",     "Oil on Canvas",        "36 x 48",      "sold",
    "myworld",          "My World",             "2012",     "Oil on Canvas",        "44 x 50",      "sold",
    "atdocks",          "At Docks",             "2011",     "Oil on Canvas",        "44 x 50",      "sold",
    "stacks",           "Stacks",               "2011",     "Oil on Canvas",        "44 x 50",      "sold",
    "transparent",      "Transparent",          "2011",     "Oil on Canvas",        "20 x 24",      "available",
    "industrial bay",   "Industrial Bay",       "2011",     "Oil on Canvas",        "46 x 50",      "available",
    "foundation",       "Foundation",           "2011",     "Oil on Canvas",        "46 x 50",      "sold",
    "headdress",        "Head Dress",           "2011",     "Oil on Canvas",        "52 x 44",      "sold",
    "genesis",          "Genesis",              "2011",     "Oil on Canvas",        "52 x 44",      "sold",
    "industrial",       "Industrial",           "2011",     "Oil on Canvas",        "48 x 40",      "sold", 
    "bayarea",          "Bay Area",             "2011",     "Oil on Canvas",        "36 x 48",      "available",
    "mycorset",         "My Corset",            "2011",     "oil on cansas",        "48 x 42",      "sold",
    "attached",         "Attached",             "2011",     "Oil on Canvas",        "48 x 42",      "sold",
    "momsmemory",       "In Mothers Memory",    "2011",     "Oil on Canvas",        "48 x 56",      "sold",
    "shastatea",        "Shasta Tea Cup",       "2011",     "Oil on Canvas",        "44 x 55",      "sold",
    "ghostdancer1",     "Ghost Dancer",         "2011",     "Oil on Canvas",        "52 x 44",      "sold",
    "rainbowl",         "Rain Bowl",            "2011",     "Oil on Canvas",        "56 x 44",      "sold",
    "catcher",          "Catcher",              "2011",     "Oil on Canvas",        "48 x 52",      "available",
    "lookingback",      "Looking Back",         "2011",     "Oil on Canvas",        "56 x 48",      "available",
    "creature",         "Creature",             "2011",     "Oil on Canvas",        "36 x 52",      "sold",
    "weavingpaint",     "Weaving Paint",        "2011",     "Oil on Canvas",        "36 x 48",      "sold",
    "neoncity",         "Neon City",            "2011",     "Oil on Canvas",        "46 x 50",      "sold",
    "myrainbow",        "My Rainbow",           "2011",     "Oil on Canvas",        "48 x 56",      "sold",
    "urbanplayground",  "Urban Playground",     "2011",     "Oil on Canvas",        "48 x 56",      "sold", 
    "object",           "Object",               "2011",     "Oil on Canvas",        "46 x 56",      "sold",
    "softandtender",    "Soft and Tender",      "2011",     "Oil on Canvas",        "48 x 56",      "sold",
    "theclearing",      "The Clearing",         "2011",     "Oil on Canvas",        "52 x 44",      "sold",
    "sffog",             "S.F. Fog",            "2011",     "Oil on Canvas",        "32 x 42",      "sold",    
    "bluedot",          "Blue Dot",             "2011",     "Oil on Canvas",        "52 x 54",      "sold",
    "peoplessole",      "Peoples Sole",         "2011",     "Oil on Canvas",        "50 x 64",      "sold",
    "thedocks",         "The Docks",            "2011",     "Oil on Canvas",        "48 x 48",      "sold",
    "suspend",          "Suspend",              "2011",     "Oil on Canvas",        "48 x 48",      "available",
    "cheers",           "Cheers",               "2011",     "Oil on Canvas",        "24 x 30",      "available", 
    "twodegrees",       "Two Degrees",          "2011",     "Oil on Canvas",        "52 x 60",      "available",
    "oceania",          "Oceania",              "2011",     "Oil on Canvas",        "52 x 44",      "sold",
    "dreamcircus",      "Dream Circus",         "2011",     "Oil on Canvas",        "52 x 60",      "sold",
    "frosttag",         "Frost Tag",            "2011",     "Oil on Canvas",        "20 x 16",      "sold",
    "secretinsketch",   "Secret in Sketch",     "2011",     "Oil on Canvas",        "54 x 64",      "sold",
    "spill",            "Spill",                "2011",     "Oil on Canvas",        "52 x 64",      "available",
    "mystery",          "Mystery",              "2011",     "Oil on Canvas",        "52 x 64",      "available",
    "falls",            "Falls",                "2011",     "Oil on Canvas",        "54 x 65",      "sold",
    "screen",           "Screen",               "2011",     "Oil on Canvas",        "48 x 54",      "available",
    "walltheory",       "Wall Theory",          "2010",     "Oil on Canvas",        "60 x 72",      "sold",  
    "oldschool",        "Old School",           "2010",     "Oil on Canvas",        "36 x 48",      "available",   
    "student",          "Student",              "2010",     "oil on cvanvas",       "36 x 48",      "available", 
    "wipedout",         "Wiped Out",            "2010",     "oi on canvas",         "48 x 60",      "sold",
    "mistyday",         "Misty Day",            "2010",     "oil on ccanvas",       "36 x 60",      "available",
    "blueseason",       "Blue Season",          "2010",     "Oil on Canvas",        "48 x 48",      "available",
    "reflection",       "Reflection",           "2010",     "Oil on Canvas",        "48 x 60",      "sold",
    "power",            "Power",                "2011",     "Oil on Canvas",        "48 x 56",      "sold", 
    "scratchbounce",    "Scratch And Bounce",   "2010",     "Oil on Canvas",        "36 x 48",      "sold",
    "nameit1",          "Name It 1",            "2010",     "Oil on Canvas",        "36 x 48",      "sold",
    "jerryspassage",    "Jerry's Passage",      "2010",     "Oil on Canvas",        "60 x 48",      "available",
    "turningcorner",    "Turning Corner",       "2010",     "Oil on Canvas",        "60 x 48",      "available",
    "chinatown",        "China Town",           "2010",     "Oil on Canvas",        "30 x 24",      "sold",
    "witchesnight",     "Witches Night",        "2010",     "Oil on Canvas",        "30 x 24",      "sold",
    "toybox",           "Toy Box",              "2010",     "Oil on Canvas",        "68 x 52",      "available",
    "scratchthrough",   "Scratch Through",      "2010",     "Oil on Canvas",        "72 x 60",      "sold",
    "childsplay",       "Childs Play",          "2010",     "Oil on Canvas",        "72 x 60",      "available",  
    "transportation",   "Transportation",       "2010",     "Oil on Canvas",        "48 x 48",      "sold",
    "openwings",        "Open Wings",           "2010",     "Oil on Canvas",        "48 x 48",      "sold",
    "outofthebox",      "Out Of the Box",       "2010",     "Oil on Canvas",        "48 x 60",      "sold",
    "indianmist",       "Indian Mist",          "2010",     "Oil on Canvas",        "30 x 40",      "sold",  
    "fiesta",           "Fiesta",               "2010",     "Oil on Canvas",        "58 X 78",      "sold", 
    "stockings",        "Stockings",            "2010",     "Oil on Canvas",        "48 x 60",      "sold",
    "docked",           "Docked",               "2010",     "Oil on Canvas",        "48 x 72",      "sold",
    "Dreaming",         "Dreaming",             "2010",     "Oil on Canvas",        "30 x40",       "sold",
    "chantersbridge",   "Chanters Bridge",      "2010",     "Oil on Canvas",        "36 x 48",      "available",   
    "warrior",          "Warrior",              "2010",     "Oil on Canvas",        "36 x 48",      "sold",
    "fallingarrow",     "Falling Arrow",        "2010",     "Oil on Canvas",        "58 x 48",      "available",
    "scratchingthrough","Scratching Through",   "2010",     "Oil on Canvas",        "53 x 59",      "available",
    "rainbowexcavation","Rainbow Excavation",   "2010",     "Oil on Canvas",        "30 x 40",      "sold",  
    "viewinside",       "View Inside",          "2010",     "Oil on Canvas",        "30 x 40",      "available",
    "brokentreaty",     "Broken Treaty",        "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "cooler",           "Cooler Enviroment",    "2010",     "Oil on Canvas",        "36 x 24",      "sold",
    "ensueno",          "Ensueno",              "2010",     "Oil on Canvas",        "30 x 40",      "sold",  
    "teacup",           "Tea Cup",              "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "rainbow",          "Rainbow",              "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "snow",             "Snow Cone Man",        "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "bridge",           "Grid and Bridges",     "2010",     "oil and canvas",       "30 x 40",      "sold",
    "entrance",         "Entrance",             "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "mycasa",           "My Casa",              "2010",     "Oil on Canvas",        "34 x 46",      "sold",  
    "scribbles",        "Scribbles",            "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "nameit",           "Name It",              "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "atomicteepee",     "Atomic Tee Pee",       "2010",     "Oil on Canvas",        "30 x 40",      "sold",
    "dreamcatcher",     "Dream Catcher",        "2010",     "Oil on Canvas",        "30 x 40",      "available",
    "nothingness",      "Nothingness",          "2010",     "Oil on Canvas",        "24 x 36",      "sold",
    "foglift",          "Fog Lifting",          "2010",     "Oil on Canvas",        "24 x 36",      "sold",
    "windows",          "Windows",              "2010",     "Oil on Canvas",        "16 x 19.5",    "sold"
    
    ];
    
    $abstract = [
    "allthat",          "All That",             "2014",     "oil on canvas",        "48 x 52",      "sold",
    "fishboat",         "Fish Boat",            "2014",     "oil on canvas",        "48 x 58",      "sold",
    "pouringout",       "Pouring Out",          "2014",     "oil on canvas",        "40 x 40",      "sold",
    "insomnia",         "Insomnia",             "2014",     "oil on canvas",        "48 x 80",      "available",
    "tribalteepee",     "Tribal Tee Pee",       "2014",     "oil on canvas",        "48 x 60",      "sold",
    "hulu",             "Hulu",                 "2016",     "oil on canvas",        "18 x 24",    "sold",
    "outofwater",		"Out of Water",			"2010",		"Oil on 2 Canvases",	"48 x 72",		"sold",
    "moccasinlake",     "Moccasin Lake",        "2010",     "Oil on Canvas",        "24 x 36",      "sold",
    "poppingout",       "Popping Out",          "2010",     "Oil on Canvas",        "36 x 48",      "sold",
    "arrowfeather",     "Arrow Feather Sails",  "2010",     "Oil on Canvas",       "30 x 36",       "sold",
    "bluespot",         "Blue Spot",            "2010",     "Oil on Canvas",        "29 x 36",      "available",
    "vessels",          "Vessels",              "2010",     "Oil on Canvas",        "48 x 36",      "sold",
    "powwow",           "Pow Wow",              "2010",     "Oil on Canvas",        "48 x 48",      "sold",
    "angles",           "Angles",               "2010",     "Oil on Canvas",        "36 x 48",      "sold",
    "birdonawire",   	"Bird On A Wire",       "2010",     "Oil on Canvas",        "48 x 48",      "sold",
    "gette",            "Gette",                "2007",     "Oil on Canvas",        "36 x 48",      "available",
    "mylovingoso",      "My Loving Oso",        "2009",     "Oil on Canvas",        "50 x 40",      "available",
    "lookingglass",     "Looking Glass",        "2009",     "Oil on Canvas",        "58 x 62",      "sold",
    "dreaming fields",  "Dreaming Fields",      "2009",     "Oil on Canvas",        "36 x 48",      "sold",
    "dreamweaver",      "Dream Weaver",         "2009",     "Oil on Canvas",        "36 x 48",      "sold",
    "explosion", 		"Explosion",			"2008",		"Oil on 2 canvases",	"36 x 72",		"sold",
    "paintsplotch", 	"Paint Splotch",		"2008",		"Oil on Canvas",		"36 x 48",		"sold",
    "cameo", 			"Cameo",				"2008",		"Oil on Canvas",		"60 x 48",		"sold",
    "shaman", 			"Shaman",				"2008",		"Oil on Canvas",		"36 x 48",		"sold",
    "wonder", 			"Wonder",				"2008",		"Oil on Canvas",		"60 x 48",		"sold",
    "tribal", 			"Tribal",				"2008",		"Oil on Canvas",		"36 x 48",		"avasilable",
    "pushing", 			"Pushing Black",		"2009",		"Oil on 2 canvases",	"72 x 36",		"sold",
    "panels", 			"Panels",				"2008",		"Oil on 2 canvases",	"72 x 48", 		"sold",
    "inside", 			"Inside",				"2008",		"Oil on Canvas",		"36 x 48",		"available",
    "bowl",				"Bowl",					"2007",		"Oil on Canvas", 		"34 x 60",		"sold",	
    "bear",				"Bear",					"2007",		"Oil on Canvas",		"36 x 48",		"available",
    "rosebud",          "Rose Bud",             "2007",     "Oil on Canvas",        "36 x 48",      "sold",
    "newyear",          "New Year",             "2007",     "Oil on Canvas",        "36 x 36",      "sold",
    "childlike",        "Childlike",            "2004",     "Oil on Canvas",        "55 x 65",      "sold",
    "iceland",          "Iceland",              "2007",     "Oil on Canvas",        "48 x 48",      "sold",
    "funny",            "Funny Pages",          "2008",     "Oil on Canvas",        "36 x 48",      "sold",
    "animated",         "Animated",             "2008",     "Oil on Canvas",        "36 x 48",      "sold",
    "catsanddogs",      "Cats and Dogs",        "2010",     "Oil on Canvas",        "30 x 24",      "sold",
    "burst", 			"Burst",				"2007", 	"Oil on Canvas",		"36 x 48",		"sold",
    "child", 			"Child",				"2007", 	"Oil on Canvas",		"36 x 48",		"available",
    "emc2", 			"EMC2",					"2007", 	"Oil on Canvas",		"36 x 48",		"sold",
    "fold", 			"Fold",					"2007", 	"Oil on Canvas",		"36 x 48",		"sold",
    "dreams", 		    "Dreams",		        "2006", 	"Oil on Canvas",		"40 x 60",		"sold",
    "oval", 			"Oval",				    "2007", 	"Oil on Canvas",		"14 x 18",		"available",
    "abbey", 		    "Abbey",				"1998",		"Oil on Canvas",		"48 x 72",		"sold",
    "acuatico", 		"Acuatico",				"2008",		"Oil on Canvas",		"36 x 48",		"sold",	
    "cityscape", 		"Cityscape",			"2008",		"Oil on Canvas",		"36 x 48",		"sold",
    "secret", 			"Secret",				"2006",		"Oil on cavas",			"36 x 48",		"available",
    "masquerade", 	    "Masquerade", 			"2007", 	"Oil on Canvas", 		"48 x 48",		"sold",
    "action", 			"Action", 				"2007", 	"Oil on Canvas", 		"48 x 48", 		"available",
    "atmosphere", 		"Atmosphere", 			"2007", 	"Oil on Canvas", 		"60 x 48",		"sold",
    "cricket", 			"Cricket",				"2007", 	"Oil on Canvas", 		"48 x 48", 		"available",
    "frosted", 			"Frosted", 				"2007", 	"Oil on Canvas", 		"60 x 48",		"sold",
    "livingcolor", 		"Living Color", 		"2007", 	"Oil on Canvas", 		"36 x 48", 	    "solde",
    "turtle", 			"Turtle", 				"2007", 	"Oil on Canvas", 		"48 x 48", 		"available",
    "wildriver", 		"Wild River", 			"2008", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "sensation", 		"Sensation", 			"2004", 	"Oil on Canvas", 		"56 x 42", 	    "sold",
    "corazones", 		"Corazones", 			"2008", 	"Oil on Canvas", 		"36 x 48", 		"sold",
    "icerose", 			"Ice Rose", 			"2008", 	"Oil on Canvas", 		"36 x 48", 		"sold",
    "antiquity",		"Antiquity",			"2007",		"Oil on Canvas",		"52 x 42",		"available",
    "midnight",			"Midnight",				"2010",		"Oil on Canvas",		"30 x 24",		"sold",
    "movement",			"Movement",				"2010",		"Oil on Canvas",		"68 x 52",		"sold",
    "rest",				"Rest",					"2010",		"Oil on Canvas",		"68 x 52",		"sold",
    "resurrection",		"Resurrection",			"2010",		"Oil on Canvas",		"68 x 52",		"sold",
    "robots",			"Robots",				"2010",		"Oil on Canvas",		"30 x 40",		"sold",
    "spin",				"Spin",					"2010",		"Oil on Canvas",		"58 x 60",		"sold",
    "oneinchoff",		"One Inch Off",			"2010",		"Oil on 2 Canvases",	"60 x 40",		"sold"
    ];
    
  $figurative = [
    "americanfolk",     "American Folk",       "2018",     "oil on canvas",      "48 x 29.5",  "available",
    "capturedsilence",  "Captured Silence",      "2017",    "oil on canvas",        "36 x 54",    "sold",
    "missyou",          "Miss You",             "2017",     "oil on canvas",        "30 x 24",    "available",
    "dotell",           "DO Tell",              "2017",     "oil on canvas",        "30 x 24",    "sold",
    "curious",           "Curious",             "2017",     "oil on canvas",        "18 x 14",     "sold",
    "dreamer",          "Dreamer",              "2017",     "oil on canvas",        "18 x 14",     "sold",
    "inthenow",         "In The Now",           "2017",     "oil on canvas",        "12 x 24",     "available",
    "brokenpromises",   "Broken Promises",      "2017",     "oil on canvas",        "17 x 24",     "available",
    "silencekills",     "Silence Kills",        "2017",     "oil on canvas",        "24 x 30",      "available",
    "resister",         "Resister",             "2017",     "oil on canvas",        "24 x 30",     "availabe",
    "hello",            "Hello",                "2003",     "oil on canvas",        "36 x 48",      "available",
    "deeplyblue",       "Deeply Blue",          "2017",     "oil on canvas",        "24 x 30",      "available",
    "decisions",       "Decisions",             "2017",     "oil on paper",        "44 x 33",       "available",
    "twinone",           "Twin One",             "2016",     "oil on canvas",      "18 x 20",      "available",
    "twintwo",           "Twin Two",             "2016",     "oil on canvas",       "18 x 20",      "available",
    "angerman",			"Anger Man",			"2010",		"Oil on Canvas",		"36 x 48",		"available",
    "bluesman",         "Blues Man",            "2011",     "Oil on Canvas",        "16 x 20",      "sold",
    "innerme",          "Inner Me",             "2004",     "Oil on Canvas",        "16 x 20",      "sold",
    "attitude",         "Attitude",             "2011",     "Oil on Canvas",        "16 x 20",      "sold",   
    "jesus",            "Jesus",                "2001",     "Oil on Canvas",        "56 x 64",      "sold",
    "survivor",          "Survivor",            "2016",     "Oil on Canvas",        "48 x 29",      "sold",
    "theman",           "The Man",              "2016",     "Oil on Canvas",        "30 x 24",      "sold",    
    "birdcompanion",    "Bird Companion",       "2003",     "Oil on Canvas",        "54 x 54",      "available",
    "intersex",         "Intersex",             "2011",     "Oil on Canvas",        "30 x 40",      "sold",
    "cocky",            "Cocky",                "2004",     "Oil on Canvas",        "36 x 48",      "sold",
    "lookhand",         "Look Hand",            "2003",     "Oil on Canvas",        "52 x 53",      "sold",
    "blame",            "Blame",                "2000",     "Oil on Canvas",        "47 x 62",      "sold",
    "evolution", 		"Evolution",			"2003",		"Oil on 2 canvases",	"60 x 40",		"available",
    "flow",				"Flower Power",			"2003",		"Oil on Canvas",		"53 x 52",		"sold",
    "foggy", 			"Foggy",				"2003",		"Oil on Canvas", 		"43 x 42",		"sold",
    "krishna", 			"Krishna", 				"2003", 	"Oil on Canvas", 		"36 x 59",		"available",
    "01",	             "01", 		            "2004", 	"Oil on Canvas", 		"36 x 48", 		"sold",
    "moderninfluence",	"Modern Influence",		"2004", 	"Oil on Canvas", 		"50 x 67",		"sold",
    "pleasepeace",		"Please Peace", 		"2004", 	"Oil on Canvas", 		"52 x 72", 		"sold",
    "lookhere",		    "Look Here",			"2000", 	"Oil on Canvas", 		"53 x 50",     "sold",
    "trueself",	        "True Self", 		    "2000", 	"Oil on Canvas", 		"36 x 48", 		"sold",
    "xyz",				"XYZ", 					"2004", 	"Oil on Canvas", 		"48 x 36", 		"sold",
    "fire",				"Fire",					"2000",		"Oil on Canvas",		"20 x 30",      "sold",
    "americannickle",   "American Nickle",		"2000",		"Oil on Canvas", 		"36 x 48",		"sold",
    "theydid",			"They Did",				"2000",		"Oil on Canvas",		"48 x 48",		"sold",
    "birdmount",		"Bird Mount",			"2000",		"Oil on Canvas",		"36 x 48",		"available",
    "churchandstate",	"Church and State",		"2000",		"Oil on Canvas",		"48 x 55",		"sold",
    "disappearing",		"Disappearing",			"2000",		"Oil on Canvas",		"30 x 40",		"sold",
    "institches",	    "In Stitches",		    "2016",		"Oil on Canvas",		"24 x 18",		"sold",
    "kevin",			"Kevin",				"2000",		"Oil on Canvas",		"34 x 44",		"sold",
    "krishna",			"Krishna",				"2000",		"Oil on Canvas",		"36 x 59",		"available",
    "circles",			"circles",				"2004",		"Oil on Canvas",		"36 x 48",		"sold",
    "letgo",			"Let Go",				"2000",		"Oil on Canvas",		"30 x 40",		"available",
    "offcross",			"Off Cross",			"2010",		"Oil on Canvas",		"36 x 48",		"sold",
    "dream",			"dream",				"2008",		"Oil on Canvas",		"36 x 48",		"available",
    "nopointing",		"No Pointing",			"2010",		"Oil on Canvas",		"36 x 48",		"sold",
    "offering",			"Offering",				"2010",		"Oil on Canvas",		"57 x 60",		"sold"
    ];
    
    $landscape = [
    "summerbox",        "Summer Box",           "2004",     "oil on canvas",        "48 x 48",      "sold",
    "redline",			"Red Line",				"2004",		"Oil on Canvas",		"48 x 48",		"sold",
    "contrast",			"Contrast",				"2004",		"Oil on Canvas",		"48 x 48",		"sold",
    "marsh",            "Marsh",                "2004",     "Oil on Canvas",        "48 x 48",      "sold",
    "mteagle",          "Mt Eagle",             "2004",     "Oil on Canvas",        "36 x 48",      "sold",
    "featherfish",      "Feather Fish",         "2005",     "Oil on Canvas",        "36 x 48",      "sold",
    "fivetrees",        "Five Trees",           "2004",     "Oil on Canvas",        "36 x 48",      "sold",
    "california",		"California", 			"2004", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "warm",			    "Warm",			        "2004",		"Oil on Canvas",		"48 x 48",		"sold",
    "mt.water",			"Mt. Water", 			"2004", 	"Oil on Canvas", 		"36 x 48",		"sold",
    "skyview",			"Sky View", 			"2004", 	"Oil on Canvas", 		"48 x 60", 		"sold",
    "heartland",		"Heartland", 			"2004", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "bayview",			"Bayview", 			    "2005", 	"Oil on Canvas", 		"48 x 72", 		"sold",
    "saltbed",			"The Saltbeds", 		"2005", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "waterline",		"The Waterline", 		"2005", 	"Oil on Canvas", 		"48 x 48",      "sold",
    "flatstudy",		"Flat Study",		    "2005",		"Oil on Canvas",		"48 x 48",		"sold",
    "beach",			"Beach",				"2000",		"Oil on Canvas",		"48 x 48",		"sold",
    "gridview",			"Grid View",			"2000",		"Oil on Canvas",		"48 x 48",		"sold",
    "storm",			"Storm",				"2000",		"Oil on Canvas",		"48 x 48",		"sold",
    "west",             "West",                 "2004",     "Oil on Canvas",        "48 x 48",      "sold",
    "fall",             "Fall",                 "2005",     "oil on canvas",        "36 x 48",      "sold",
    ];
    
    
    
    

$lists = [$social, $abstract, $figurative, $landscape];

$inputs = 6;

foreach($lists as $listIndex => $list) {
    $datumCount = count($list);
    $totalEntries = $datumCount / $inputs;
    echo "Total entries: ".$totalEntries;

//    print_r($list);
    for ($i=0; $i < $datumCount; $i++) {
       // echo $i .": ".$list[$i];
       // echo "<br>";
        $nothing = $list[$i++];
        $title = $list[$i++];
        $year = $list[$i++];
        $nothing2 = $list[$i++];
        $size = $list[$i++];
        $sold = $list[$i];

        $artwork = new artworks(['','','','','','','','','']);

        $artwork->title = $title;
        $thisdate = new DateTime('January 1, '.$year);
        $artwork->created = $thisdate->format( 'Y-m-d H:i:s');
        
        $width = '0';
        $exploded_width = explode(' x ',$size);
        if (count($exploded_width) > 0) {
            $width = $exploded_width[0];
        }
        $artwork->width = $width;
        $height = '0';
        $exploded_height = explode(' x ',$size);

        if (count($exploded_height) > 1) {
            $height = $exploded_height[1];
        }
        $artwork->height = $height;

        $artwork->sold = ($sold=='sold'? 1:0);
        $artwork->category = $cats[$listIndex];
        $artwork->save();
        // echo "artwork:<br>";
        // echo "title: ".$artwork->title."<br>";
        // echo "width: ".$artwork->width."<br>";
        // echo "height: ".$artwork->height."<br>";
        // echo "created: ".$artwork->created."<br>";
        // echo "sold: ".$artwork->sold."<br>";
        // echo "---<br>";
        // echo "<br>";

    }

}

    //
    /*

     "contrast",		"Contrast",				"2004",		"Oil on Canvas",		"48 x 48",		"sold",
    "marsh",            "Marsh",                "2004",     "Oil on Canvas",        "48 x 48",      "sold",
    "mteagle",          "Mt Eagle",             "2004",     "Oil on Canvas",        "36 x 48",      "sold",
    "featherfish",      "Feather Fish",         "2005",     "Oil on Canvas",        "36 x 48",      "sold",
    "fivetrees",        "Five Trees",           "2004",     "Oil on Canvas",        "36 x 48",      "sold",
    "california",		"California", 			"2004", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "warm",			    "Warm",			        "2004",		"Oil on Canvas",		"48 x 48",		"sold",
    "mt.water",			"Mt. Water", 			"2004", 	"Oil on Canvas", 		"36 x 48",		"sold",
    "skyview",			"Sky View", 			"2004", 	"Oil on Canvas", 		"48 x 60", 		"sold",
    "heartland",		"Heartland", 			"2004", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "bayview",			"Bayview", 			    "2005", 	"Oil on Canvas", 		"48 x 72", 		"sold",
    "saltbed",			"The Saltbeds", 		"2005", 	"Oil on Canvas", 		"48 x 48", 		"sold",
    "waterline",		"The Waterline", 		"2005", 	"Oil on Canvas", 		"48 x 48",      "sold",
    "flatstudy",		"Flat Study",		    "2005",		"Oil on Canvas",		"48 x 48",		"sold",
    "beach",			"Beach",				"2000",		"Oil on Canvas",		"48 x 48",		"sold",
    "gridview",			"Grid View",			"2000",		"Oil on Canvas",		"48 x 48",		"sold",
    "storm",			"Storm",				"2000",		"Oil on Canvas",		"48 x 48",		"available"
  
    */
?>


